steps:
  # 1. Build the container image
  # The 'dir' property tells Cloud Build to run this step inside the 'src/backend' folder.
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'src/backend' # Add this line
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/druv-backend:$COMMIT_SHA', '.']

  # 2. Push the container image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/druv-backend:$COMMIT_SHA']

  # 3. Deploy the container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'druv-backend'
      - '--image=gcr.io/${PROJECT_ID}/druv-backend:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/${PROJECT_ID}/druv-backend:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY